[package]
name = "demo_app"
version = "0.1.0"
authors = ["root"]
edition = "2018"

[dependencies]
rand = "0.4.0"
num = "0.1.27"
image = "0.13.0"
crossbeam = "0.2.8"
threadpool = "1.7.1"
num_cpus = "1.10.0"
error-chain = "0.9.0"